services:
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - maputnik

  maputnik:
    image: ghcr.io/maplibre/maputnik:main
    restart: unless-stopped
    expose:
      - "80"

  devenv:
    image: ghcr.io/maplibre/workshop:latest
    restart: unless-stopped
    command: sleep infinity
