version: "3.8"

services:
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - martin
      - maputnik

  maputnik:
    image: ghcr.io/maplibre/maputnik:main
    restart: unless-stopped
    expose:
      - "80"

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - data:/data
    command:
      - /data/estonia.mbtiles

  planetiler:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    volumes:
      - data:/data
    command: sleep infinity

volumes:
  data:
